apiVersion: v1
kind: Pod
metadata:
  name: netdata
spec:
  securityContext:
    runAsUser: 0 # All containers in the pod will run as root
    privileged: true # Enable privileged mode for all containers (if applicable)
    capabilities:
      add:
        - ALL # Add all capabilities for all containers
  containers:
    - name: netdata
      image: netdata/netdata:v1.29.0
      ports:
        - containerPort: 19999
          name: 19999tcp
          protocol: TCP
      volumeMounts:
        - mountPath: /var/log/nginx
          name: logs
        - mountPath: /etc/netdata/netdata.conf
          name: netdata-config
          subPath: netdata.conf
        - mountPath: /var/lib/netdata
          name: netdata-writable

