apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-server-conf
            defaultMode: 420
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Netdata for live storage
      - job_name: "netdata"
        scrape_interval: 10s
        scrape_timeout: 10s
        metrics_path: /api/v1/allmetrics
        params:
          format: ['prometheus']
        scheme: http
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: webserver
          - source_labels: [__address__]
            target_label: __address__
            replacement: netdata-service.monitoring.svc.cluster.local:19999
    remote_write:
      # Remote write for live storage (Netdata)
      - url: http://vminsert-live.monitoring.svc.cluster.local:8480/insert/0/prometheus
        queue_config:
          capacity: 10000
          max_shards: 5
        write_relabel_configs:
          - source_labels: [__name__]
            regex: "netdata.*"
            action: keep

      # Remote write for longterm storage (Prometheus)
      - url: http://vminsert-longterm.monitoring.svc.cluster.local:8480/insert/0/prometheus
        queue_config:
          capacity: 10000
          max_shards: 5
        write_relabel_configs:
          - source_labels: [__name__]
            regex: "prometheus.*"
            action: keep

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
